source:
  repo: "https://github.com/immortalwrt/immortalwrt"
  branch: "openwrt-25.12"

target:
  arch: "x86"
  subtarget: "x86_64"
  device: "generic x86_64"
  # device: "multiple devices"
  # devices:
  #   - "generic x86_64"

feeds:
  - name: nikki
    url: https://github.com/nikkinikki-org/OpenWrt-nikki
    branch: main

build:
  language: zh-cn
  use_ccache: true

image:
  filesystems:
    #- ext4
    - squashfs
  initramfs: false
  recovery: false
  #legacy_boot: true
  uefi_boot: true
  kernel_partition_mb: "32"
  rootfs_size_mb: "512"
  pve: false
  vmware: false
  hyperv: false

output:
  artifact: false
  webdav: true

upload:
  webdav_path: /openwrt