source:
  repo: "https://github.com/immortalwrt/immortalwrt"
  branch: "openwrt-25.12"

target:
  arch: "x86"
  subtarget: "x86_64"
  device: "generic x86_64" # 编译多设备时写"multiple devices"，同时使用下方字段指定设备
  #devices:
  #  - "generic x86_64"

feeds:
  - name: nikki
    url: https://github.com/nikkinikki-org/OpenWrt-nikki
    branch: main

extra_packages:
  - name: easytier
    url: https://github.com/EasyTier/luci-app-easytier
    dir: package/luci-app-easytier

build:
  language: zh-cn
  use_ccache: true

image:
  filesystems:
    #- ext4
    - squashfs
  initramfs: false
  recovery: false
  legacy_boot: false
  uefi_boot: true
  kernel_partition_mb: "32"
  rootfs_size_mb: "512"
  pve: false
  vmware: false
  hyperv: false

output:
  artifact: true
  webdav: false

upload:
  webdav_path: /openwrt